
export const REQUEST_WEATHER = 'REQUEST_WEATHER'
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const CONVERT_DATE_TIME = 'CONVERT_DATE_TIME'